# Mini projekt PAD - scrapper danych o oponach
## Jakub Michalak S20034
### Opis projektu
- Projekt polega na pobraniu danych o oponach z dwóch sklepów internetowych: sklep opon i oponeo
- Dane pobrane z obu sklepów zostaną zapisane w plikach CSV
- Dane zostaną oczyszczone i przygotowane do analizy

In [2]:
import pandas as pd
import re
import time

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

# Scrapping danych
### Konfiguracja drivera do scrapowania danych 
- **Uwaga**: testowane na szerokości okna 1110 pikseli
- Ustawienie szerokości okna na 1100 pikseli pozwala na poprawne działanie skryptów do scrapowania danych ze stron sklep opon i oponeo. Przy wyższej szerokości okna mogą wystąpić problemy z lokalizacją elementów na stronie (np. oceny).

In [117]:
download_service = Service()
driver = webdriver.Chrome(service=download_service)
driver.set_window_size(1100, 800)

sklep_opon_base_url = "https://www.sklepopon.com/szukaj-opony?sezon=zimowe&rozmiar=205/55R16&ofs="
oponeo_base_url = "https://www.oponeo.pl/wybierz-opony/s=1/zimowe/t=1/osobowe/r=1/205-55-r16"

### Funkcje obsługujące scrapowanie danych ze stron sklep opon i oponeo

In [3]:
def close_sklep_opon_popups(outer_driver):
    try:
        btn_cookie = outer_driver.find_element(By.CSS_SELECTOR, "#klaro > div > div > div > div > div > button")
        btn_cookie.click()
        print("Przycisk akceptacji ciasteczek został kliknięty.")
    except NoSuchElementException:
        print("Przycisk akceptacji ciasteczek nie został znaleziony.")
    except Exception as exception:
        print("Nie udało się kliknąć przycisku akceptacji ciasteczek:", exception)
    
    try:
        outer_driver.execute_script("""
            const shadowHost = document.querySelector("body > div.gr-visual-prompt");
            if (shadowHost) {
                const shadowRoot = shadowHost.shadowRoot;
                const closeButton = shadowRoot.querySelector("div > div:nth-child(2) > button:nth-child(1)");
                if (closeButton) {
                    closeButton.click();
                    console.log("Okienko powiadomień zostało zamknięte.");
                } else {
                    console.log("Nie znaleziono przycisku zamknięcia powiadomień.");
                }
            } else {
                console.log("Okno powiadomień nie zostało znalezione.");
            }
        """)
    except Exception as exception:
        print("Nie udało się zamknąć okienka powiadomień:", exception)

def close_oponeo_popup(outer_driver):
    try:
        reject_button = outer_driver.find_element(By.CSS_SELECTOR, "#consentsBar > div.buttonsContainer.container > div > span.reject")
        reject_button.click()
        print("Okienko prywatności zostało zamknięte.")
    except NoSuchElementException:
        print("Okienko prywatności nie jest widoczne lub zostało już zamknięte.")
    except Exception as e:
        print("Wystąpił błąd podczas zamykania okienka prywatności:", e)
        
def load_sklep_opon_tire_data(outer_driver):
    scrapped_data = []
    try:
        opony_elements = outer_driver.find_elements(By.CSS_SELECTOR, 'div[data-c-name="listing-products-element"]')
            
        class_mapping = {
            "Premium": "Premium",
            "Średnia": "Średnia",
            "Średniej": "Średnia",
            "Ekonomiczna": "Ekonomiczna",
            "Ekonomicznej": "Ekonomiczna"
        }
        
        for opona_element in opony_elements:
            
            try:
                load_index = opona_element.find_element(By.CSS_SELECTOR, 'li[data-attribute-code="li"]').text
                speed_index = opona_element.find_element(By.CSS_SELECTOR, 'li[data-attribute-code="si"]').text
            except NoSuchElementException:
                load_index = None
                speed_index = None
            
            noise_level = None
            try:
                noise_level_elements = opona_element.find_elements(By.CSS_SELECTOR, "span.self-center.tracking-tighter.sm\\:tracking-normal")
                for noise_level_element in noise_level_elements:
                    text = noise_level_element.text
                    match = re.search(r'\d+', text)
                    if match:
                        noise_level = int(match.group())
            except (NoSuchElementException, IndexError):
                pass
            
            etykieta_elements = opona_element.find_elements(By.CSS_SELECTOR, 'span.icon-fuel-new ~ span, span.icon-rain-new ~ span, span.icon-speaker-new ~ span')
            fuel_index = etykieta_elements[0].text if len(etykieta_elements) > 0 else None
            wet_grip_index = etykieta_elements[1].text if len(etykieta_elements) > 1 else None
            noise_index = etykieta_elements[2].text.split(" ")[0] if len(etykieta_elements) > 2 else None
            
            try:
                tire_class_element = opona_element.find_element(By.XPATH, ".//*[contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'klas')]")
                tire_class_text = tire_class_element.text.lower().replace("w klasie ", "").replace("klasa ", "").strip().capitalize()
                tire_class = class_mapping.get(tire_class_text, tire_class_text)
            except NoSuchElementException:
                tire_class = None
                
            try:
                user_rating_element = opona_element.find_element(By.XPATH, ".//li[contains(@class, 'xl:hidden')]//span[contains(@class, 'ml-1')]")
                user_rating = float(user_rating_element.text.replace(",", "."))
            except NoSuchElementException:
                user_rating = None
                
            price = float(opona_element.get_attribute('data-ee-product-properties').split(";")[3].split(":")[1])
            
            # Pobranie dostępności
            try:
                availability_element = opona_element.find_element(By.CSS_SELECTOR, "div.tooltip-product-listing")
                availability_code = availability_element.get_attribute("data-attribute-code")
                
                if availability_code == "item_availability_tooltip_high":
                    availability = "full"
                elif availability_code == "item_availability_tooltip_medium":
                    availability = "medium"
                elif availability_code == "item_availability_tooltip_low":
                    availability = "low"
                elif availability_code == "item_availability_tooltip_last":
                    availability = "last"
                else:
                    availability = None
            except NoSuchElementException:
                availability = None
                
            tire_data = {
                "name": opona_element.get_attribute("data-ee-product-properties").split(";")[0].split(":")[1],
                "brand": opona_element.get_attribute("data-ee-product-properties").split(";")[4].split(":")[1],
                "model": opona_element.get_attribute("data-ee-product-properties").split(";")[6].split(":")[1],
                "size": opona_element.get_attribute("data-ee-product-properties").split(";")[5].split(":")[1],
                "load_index": load_index,
                "speed_index": speed_index,
                "fuel_index": fuel_index,
                "wet_grip_index": wet_grip_index,
                "noise_index": noise_index,
                "noise_level": noise_level,
                "class": tire_class,
                "user_rating": user_rating,
                "price": price,
                "availability": availability
            }
            
            scrapped_data.append(tire_data)
    finally:
        pass
    return scrapped_data   

def load_next_oponeo_page(web_driver, current_page_number):
    try:
        next_page_button = web_driver.find_element(By.ID, f"_ctPgrp_pi{current_page_number}i")
        next_page_button.click()
        time.sleep(2)
        return True
    except NoSuchElementException:
        return False
    
def load_oponeo_tire_data(outer_driver):
    scrapped_data = []
    products = outer_driver.find_elements(By.CLASS_NAME, "product")
    
    for product in products:
        try:
            try:
                link_element = product.find_element(By.CSS_SELECTOR, ".productName a")
                nazwa = link_element.get_attribute("title")
            except NoSuchElementException:
                nazwa = product.find_element(By.CLASS_NAME, "productName").text

            noise = product.find_element(By.CSS_SELECTOR, ".icon-noise em").text
            match = re.search(r'\d+', noise)
            if match:
                noise_level = int(match.group())
            else:
                noise_level = int(product.find_element(By.CSS_SELECTOR, ".icon-noise em").text.split()[1].replace("dB", "").strip())
             
            noise_index = product.find_element(By.CSS_SELECTOR, ".icon-noise em").text.split()[0] 
            noise_index_text = noise_index if noise_index in {"A", "B", "C", "D", "E", "F"} and len(noise_index) == 1 else None   
                
            try:
                user_rating = product.find_element(By.CSS_SELECTOR, ".productRating .note").text
                user_rating = user_rating.replace(',', '.')
            except NoSuchElementException:
                user_rating = None
                
            # Pobranie poziomu dostępności
            try:
                stock_level_element = product.find_element(By.CSS_SELECTOR, ".stockLevel")
                stock_level_class = stock_level_element.get_attribute("class").split()[-1]
                
                if stock_level_class == "full":
                    availability = "full"
                elif stock_level_class == "medium":
                    availability = "medium"
                elif stock_level_class == "low":
                    availability = "low"
                else:
                    availability = None
            except NoSuchElementException:
                availability = None
                
            tire_info = {
                "name": nazwa,
                "brand": product.find_element(By.CLASS_NAME, "producerName").text,
                "model": product.find_element(By.CLASS_NAME, "modelName").text,
                "size": product.find_element(By.CLASS_NAME, "modelSize").text,
                "load_index": product.find_element(By.XPATH, ".//span[@data-tp='TireLoadIndex']/em").text,
                "speed_index": product.find_element(By.XPATH, ".//span[@data-tp='TireSpeedIndex']/em").text,
                "fuel_index": product.find_element(By.CSS_SELECTOR, ".icon-fuel em").text,
                "wet_grip_index": product.find_element(By.CSS_SELECTOR, ".icon-rain em").text,
                "noise_index": noise_index_text,
                "noise_level": noise_level,
                "class": product.find_element(By.CLASS_NAME, "class").text.replace("KLASA ", "").capitalize(),
                "user_rating": user_rating,
                "price": product.find_element(By.CLASS_NAME, "priceValue").text,
                "availability": availability
            }
            
            scrapped_data.append(tire_info)

        except NoSuchElementException:
            pass
            
    return scrapped_data   

def update_column_types():
    # Konwersja kolumn do typów numerycznych w zbiorze df_oponeo
    df_oponeo['noise_level'] = pd.to_numeric(df_oponeo['noise_level'], errors='coerce').astype('Int64')
    df_oponeo['user_rating'] = pd.to_numeric(df_oponeo['user_rating'], errors='coerce').astype(float)
    df_oponeo['price'] = pd.to_numeric(df_oponeo['price'], errors='coerce').astype(float)
    
    # Konwersja kolumn do typów numerycznych w zbiorze df_sklep_opon
    df_sklep_opon['noise_level'] = pd.to_numeric(df_sklep_opon['noise_level'], errors='coerce').astype('Int64')
    df_sklep_opon['user_rating'] = pd.to_numeric(df_sklep_opon['user_rating'], errors='coerce').astype(float)
    df_sklep_opon['price'] = pd.to_numeric(df_sklep_opon['price'], errors='coerce').astype(float)
    
    # Konwersja kolumn z ograniczoną liczbą unikalnych wartości na typ 'category' w zbiorze df_sklep_opon
    df_sklep_opon['size'] = df_sklep_opon['size'].astype('category')
    df_sklep_opon['load_index'] = df_sklep_opon['load_index'].astype('category')
    df_sklep_opon['speed_index'] = df_sklep_opon['speed_index'].astype('category')
    df_sklep_opon['fuel_index'] = df_sklep_opon['fuel_index'].astype('category')
    df_sklep_opon['wet_grip_index'] = df_sklep_opon['wet_grip_index'].astype('category')
    df_sklep_opon['noise_index'] = df_sklep_opon['noise_index'].astype('category')
    df_sklep_opon['class'] = df_sklep_opon['class'].astype('category')
    df_sklep_opon['availability'] = df_sklep_opon['availability'].astype('category')
    
    # Konwersja kolumn z ograniczoną liczbą unikalnych wartości na typ 'category' w zbiorze df_oponeo
    df_oponeo['size'] = df_oponeo['size'].astype('category')
    df_oponeo['load_index'] = df_oponeo['load_index'].astype('category')
    df_oponeo['speed_index'] = df_oponeo['speed_index'].astype('category')
    df_oponeo['fuel_index'] = df_oponeo['fuel_index'].astype('category')
    df_oponeo['wet_grip_index'] = df_oponeo['wet_grip_index'].astype('category')
    df_oponeo['noise_index'] = df_oponeo['noise_index'].astype('category')
    df_oponeo['class'] = df_oponeo['class'].astype('category')
    df_oponeo['availability'] = df_oponeo['availability'].astype('category')
    
    # Optymalizacja pamięci - zmiana typów numerycznych na bardziej optymalne
    df_oponeo['user_rating'] = df_oponeo['user_rating'].astype('float32')
    df_oponeo['price'] = df_oponeo['price'].astype('float32')
    
    # Optymalizacja pamięci - zmiana typów numerycznych na bardziej optymalne
    df_sklep_opon['user_rating'] = df_sklep_opon['user_rating'].astype('float32')
    df_sklep_opon['price'] = df_sklep_opon['price'].astype('float32')

### Kod do pobierania danych ze strony sklep opon

In [118]:
sklep_opon_tires_data = []
offset = 0

while True:
    url = f"{sklep_opon_base_url}{offset}"
    driver.get(url)
    time.sleep(4)
    
    if offset == 0:
        close_sklep_opon_popups(driver)
    
    tires_data = load_sklep_opon_tire_data(driver)
    sklep_opon_tires_data.extend(tires_data)
    
    offset += 20
    if len(driver.find_elements(By.CSS_SELECTOR, 'div[data-c-name="listing-products-element"]')) == 0:
        print("Brak nowych danych. Koniec paginacji.")
        break

df_sklep_opon = pd.DataFrame(sklep_opon_tires_data)
display(df_sklep_opon)

Przycisk akceptacji ciasteczek został kliknięty.
Brak nowych danych. Koniec paginacji.

,name,brand,model,size,load_index,speed_index,fuel_index,wet_grip_index,noise_index,noise_level,class,user_rating,price,availability
0,Wintrac 205/55 R16 91 H,Vredestein,Wintrac,205/55 R16,91,H,C,B,B,70.0,Premium,5.4,376.99,full
1,Winguard Snow'G WH2 205/55 R16 91 H,Nexen,Winguard Snow'G WH2,205/55 R16,91,H,D,C,B,70.0,Średnia,5.3,310.00,full
2,DIMAX ALPINE 205/55 R16 94 H,Radar,DIMAX ALPINE,205/55 R16,94,H,D,C,A,69.0,Ekonomiczna,5.2,225.49,full
3,Frigo HP2 205/55 R16 91 H,Dębica,Frigo HP2,205/55 R16,91,H,C,C,B,72.0,Ekonomiczna,5.2,299.00,full
4,Frigo 2 205/55 R16 91 T,Dębica,Frigo 2,205/55 R16,91,T,C,C,B,71.0,Ekonomiczna,5.1,239.00,full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,Winter Sottozero Serie II 205/55 R16 94 V,Pirelli,Winter Sottozero Serie II,205/55 R16,94,V,C,C,B,72.0,Premium,5.5,1059.57,last
402,WINTERPRO2 (EVO)* 205/55 R16 91 T,Gt radial,WINTERPRO2 (EVO)*,205/55 R16,91,T,D,B,B,70.0,None,NaN,340.47,last
403,Ultra Grip 8 205/55 R16 91 T,Goodyear,Ultra Grip 8,205/55 R16,91,T,D,D,B,71.0,Premium,5.2,374.43,last
404,Blizzak LM005 205/55 R16 94 V,Bridgestone,Blizzak LM005,205/55 R16,94,V,C,A,B,71.0,Premium,5.5,643.11,last
405,FROSTRACK UHP 205/55 R16 91 H,Minerva,FROSTRACK UHP,205/55 R16,91,H,None,None,None,NaN,None,4.5,328.23,last

### Kod do pobierania danych ze strony oponeo

In [111]:
driver.get(oponeo_base_url)
close_oponeo_popup(driver)

all_tires_data = []

page_number = 1
while True:
    tires_data = load_oponeo_tire_data(driver)
    all_tires_data.extend(tires_data)
    
    page_number += 1
    if not load_next_oponeo_page(driver, page_number):
        print("Brak nowych danych. Koniec paginacji.")
        break

df_oponeo = pd.DataFrame(all_tires_data)
display(df_oponeo)

Okienko prywatności zostało zamknięte.
Brak nowych danych. Koniec paginacji.

,name,brand,model,size,load_index,speed_index,fuel_index,wet_grip_index,noise_index,noise_level,class,user_rating,price,availability
0,Bridgestone Blizzak LM005 205/55 R16 91 H,Bridgestone,Blizzak LM005,205/55 R16,91,H,C,A,B,71,Premium,4.7,459,full
1,Michelin Alpin 7 205/55 R16 91 H,Michelin,Alpin 7,205/55 R16,91,H,C,B,B,71,Premium,4.8,467,full
2,Dębica Frigo 2 205/55 R16 91 T,Dębica,Frigo 2,205/55 R16,91,T,C,C,B,71,Ekonomiczna,4.2,252,full
3,Kormoran Snow 205/55 R16 91 H,Kormoran,Snow,205/55 R16,91,H,D,C,B,72,Ekonomiczna,4.5,249,full
4,Firemax FM805+ 205/55 R16 91 H,Firemax,FM805+,205/55 R16,91,H,D,C,A,67,Ekonomiczna,4.4,209,full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,Continental ContiWinterContact TS830 P 205/55 ...,Continental,ContiWinterContact TS830 P,205/55 R16,91,H,D,C,B,72,Premium,4.4,760,medium
218,Goodyear UG Performance 2 205/55 R16 91 H RUN ...,Goodyear,UG Performance 2,205/55 R16,91,H,D,C,B,72,Premium,4.3,778,full
219,Bridgestone Blizzak LM005 205/55 R16 94 V XL,Bridgestone,Blizzak LM005,205/55 R16,94,V,C,A,B,71,Premium,4.7,854,medium
220,Pirelli SottoZero Serie 3 205/55 R16 91 H RUN ...,Pirelli,SottoZero Serie 3,205/55 R16,91,H,D,B,B,72,Premium,4.6,981,full
221,Michelin ALPIN 5 205/55 R16 91 H RUN ON FLAT,Michelin,ALPIN 5,205/55 R16,91,H,E,B,A,68,Premium,4.6,1 100,full

### Zamknięcie drivera po scrapowaniu danych

In [121]:
driver.quit()

### Zapisanie danych do plików CSV
- służy to do zapisania danych do plików CSV, aby można było je łatwo odtworzyć w przyszłości
- dane zapisane w plikach CSV można wczytać do DataFrame za pomocą funkcji `pd.read_csv`

In [3]:
# df_sklep_opon.to_csv("data/miniprojekt/sklep_opon.csv", index=False)
# df_oponeo.to_csv("data/miniprojekt/oponeo.csv", index=False)
df_sklep_opon = pd.read_csv("data/miniprojekt/sklep_opon.csv", delimiter=",")
df_oponeo = pd.read_csv("data/miniprojekt/oponeo.csv", delimiter=",")

### Weryfikacja poprawnych wartości w każdej kolumnie

In [10]:
print("sklep opon")
print("typy danych w kolumnach")
print(df_sklep_opon.dtypes)
print("unikalne wartości w kolumnach")
for column in df_sklep_opon.columns:
    if column not in ["name", "brand", "model"]:
        print(column, df_sklep_opon[column].unique())
print("oponeo")
print("typy danych w kolumnach")
print(df_oponeo.dtypes)
print("unikalne wartości w kolumnach")
for column in df_oponeo.columns:
    if column not in ["name", "brand", "model"]:
        print(column, df_oponeo[column].unique())

sklep opon
typy danych w kolumnach
name               object
brand              object
model              object
size               object
load_index          int64
speed_index        object
fuel_index         object
wet_grip_index     object
noise_index        object
noise_level         Int64
class              object
user_rating       float64
price             float64
availability       object
dtype: object
unikalne wartości w kolumnach
size ['205/55 R16']
load_index [94 91]
speed_index ['H' 'T' 'V' 'R']
fuel_index [nan 'D' 'C' 'E' 'B']
wet_grip_index [nan 'B' 'A' 'C' 'E' 'D']
noise_index [nan 'A' 'B' 'C']
noise_level <IntegerArray>
[<NA>, 68, 69, 71, 70, 72, 67]
Length: 7, dtype: Int64
class ['Ekonomiczna' 'Średnia' 'Premium']
user_rating [nan 5.3 5.5 5.7 5.4 5.  4.6 5.2 5.6 4.3 5.1 4.5 6.  4.8 4.4 4.9 4.7 4.2
 1.  2.5 2.3 1.4]
price [ 255.92  280.57  281.68  412.66  728.52 1168.49  826.82  460.    551.68
  306.31  527.16  536.31  444.94  502.64  619.55  587.41  496.3   450.99
  469.36  617.99  813.    653.93  348.59  347.    370.07  482.92  462.72
  430.    576.74  475.    484.81  613.27  307.12  225.49  442.32  315.61
  351.15  418.19  380.47  563.99  453.48  367.19  437.02  511.42  447.65
  508.39  389.65  582.8   240.3   301.28  512.4   355.    399.    554.41
  562.12  243.53  349.06  357.18  384.24  228.78  239.    299.    550.19
  344.82  563.93  522.25  408.6   326.06  817.4   634.39 1181.35  312.43
  524.88  423.99  319.67  229.99  234.99  338.24  341.99  343.99  372.99
  391.99  306.14  374.84  487.32  415.08  200.82  322.95  312.65  322.23
  294.94  353.12  581.78  330.12  380.06  426.38  553.49  534.43  658.41
  302.98  289.    468.05  413.74  278.63  250.53  238.12  404.6   260.47
  507.88  506.27  419.57  445.54  325.67  431.6   439.64  315.24  324.3
  312.53  411.32  228.02 2317.73  534.33  317.95 1133.57  347.29  545.99
  485.08  224.99  382.18  350.78  486.34  413.27  510.44  561.72  337.38
  341.45  244.99  221.58  410.67  358.86  491.19  257.99  393.64  436.31
  359.89  285.99  370.13  321.72  335.    385.    360.    435.    455.99
  327.42  377.24  634.11 2496.76  779.81  505.27  446.98  565.99  674.31
  542.76  531.72  770.43  533.32 1205.81  222.99  238.99  327.63  831.46
  305.77  401.76  227.08  238.68  314.19  324.17  436.58  245.    478.95
  552.43 1135.74  477.5   496.91  469.48  538.31  364.84 3542.51  588.86
  336.37  502.25  400.74  368.93  491.41  197.09  308.47  258.99  214.42
  285.84  360.81  478.49  338.76  366.57  361.3   631.1   751.58  308.72
  305.85  602.87  862.48  289.8   691.27  333.09  487.73  335.82  310.
  319.57  565.75  289.99  277.99  380.93  334.38  221.76  363.95  328.16
  358.89  269.24  312.9   325.21  760.15  572.99 1024.59  402.99  522.72
  488.99  534.01  591.63  780.47 1393.4   416.99  322.    370.    476.49
  997.45  621.17 3240.55  595.31  467.    547.99  698.62  345.    443.58
  530.12  416.75  336.89  623.32  320.    353.99  425.55  645.34  239.84
 1159.88  329.13  332.99  421.01  484.95  213.76  323.47  306.96  332.88
  376.99  355.5   518.16  752.63  227.    259.52  464.99  559.06  576.36
  981.48]
availability ['full' 'medium' 'low' 'last']
oponeo
typy danych w kolumnach
name               object
brand              object
model              object
size               object
load_index          int64
speed_index        object
fuel_index         object
wet_grip_index     object
noise_index        object
noise_level         Int64
class              object
user_rating       float64
price             float64
availability       object
dtype: object
unikalne wartości w kolumnach
size ['205/55 R16']
load_index [91 94]
speed_index ['H' 'T' 'V']
fuel_index ['D' 'C' 'B' 'E' 'F']
wet_grip_index ['C' 'E' 'D' 'B' 'A' 'F']
noise_index ['B' 'A' 'C']
noise_level <IntegerArray>
[72, 71, 69, 70, 67, 68, 73]
Length: 7, dtype: Int64
class ['Ekonomiczna' 'Średnia' 'Premium']
user_rating [5.  4.4 nan 4.5 4.7 4.6 4.8 4.3 3.8 4.2 2.6 4.  3.7 3.6 3.9 4.1 2.4]
price [320.         374.         337.         418.         267.
 380.         497.         667.         582.         655.
 661.         367.         376.         538.         468.
 533.         644.         465.         621.         491.
 459.         541.         630.         854.         631.
 257.         274.         207.         604.         760.
 474.         464.         555.         597.         513.
 331.         520.         390.         365.         298.
 270.         551.         612.         560.         567.
 409.         434.         552.         600.         252.
 311.         392.         505.         435.         373.
 209.         437.         342.         508.         511.
 283.         345.         258.         562.         461.
 584.         449.         357.         333.         423.
 330.         778.         645.         407.         583.
 703.         447.         452.         589.         668.
 346.         432.         487.         216.         217.
 215.         220.         415.         393.         339.
 348.         382.         249.         336.         254.
 414.         332.         534.         368.         518.
 269.         264.         443.         325.         301.
 335.         350.         400.         377.         395.
 536.         753.         359.26851852 467.         466.
 315.         442.         410.         440.         381.
 191.         218.         294.         293.         574.
 307.         297.         340.         359.         338.
 397.         577.         389.         371.         424.
 640.         477.         490.         387.         708.
 573.         271.         275.         334.         385.
 287.         304.         317.         483.         547.
 633.         292.         356.         701.         691.
 362.         405.         402.         401.         273.
 300.         279.         370.         388.         550.
 433.         525.         494.         379.         383.
 305.         421.         353.         455.         530.
 229.         299.        ]
availability ['full' 'medium' 'low' nan]

# Czyszczenie i przygotowanie danych

### #0. konwersja kolumn do typów numerycznych i typu category

In [18]:
update_column_types()

### Funkcje pomocnicze

In [6]:
def find_closest_key(value, param_map):
        closest_key = min(param_map, key=lambda k: abs(param_map[k] - value))
        return closest_key

def find_closest_value(value, param_map):
        closest_key = min(param_map, key=lambda k: abs(param_map[k] - value))
        return param_map[closest_key]

### #1. Uzupełnianie noise_index na podstawie noise_level

In [7]:
def update_noise_index_column(df):
    grouped_noise_index = df.groupby('noise_index')['noise_level'].mean().round().astype(int)
    
    if 'C' not in grouped_noise_index:
        if 'B' in grouped_noise_index and 'A' in grouped_noise_index:
            grouped_noise_index['C'] = grouped_noise_index['B'] + (grouped_noise_index['B'] - grouped_noise_index['A'])
    
    noise_map = grouped_noise_index.to_dict()
    
    def apply_update_noise_index(row):
        if pd.notna(row['noise_level']) and pd.isna(row['noise_index']):
            return find_closest_key(row['noise_level'], noise_map)
        return row['noise_index']
    
    df['noise_index'] = df.apply(apply_update_noise_index, axis=1)
    
    return df

df_oponeo = update_noise_index_column(df_oponeo)
df_sklep_opon = update_noise_index_column(df_sklep_opon)

print("Zaktualizowano noise_index")
print(df_oponeo['noise_index'].unique())
print(df_sklep_opon['noise_index'].unique())

Zaktualizowano noise_index
['B' 'A' 'C']
['B' 'A' nan 'C']

### #2. Uzupełnianie ceny na podstawie średniej ceny i klasy na podstawie ceny

In [8]:
def update_price_column(df):
    class_price_map = df.groupby('class')['price'].mean().to_dict()
    
    def apply_update_price(row):
        if pd.isna(row['price']):
            return find_closest_value(row['price'], class_price_map)
        return row['price']
    
    def apply_update_class(row):
        if pd.isna(row['class']):
            return find_closest_key(row['price'], class_price_map)
        return row['class']
    
    df['price'] = df.apply(apply_update_price, axis=1)
    df['class'] = df.apply(apply_update_class, axis=1)
    
    return df

df_oponeo = update_price_column(df_oponeo)
df_sklep_opon = update_price_column(df_sklep_opon)

print("Zaktualizowano cenę i klasę")
print("oponeo")
print(df_oponeo['price'].unique())
print(df_oponeo['class'].unique())
print("sklep opon")
print(df_sklep_opon['price'].unique())
print(df_sklep_opon['class'].unique())

Zaktualizowano cenę i klasę
oponeo
[459.         467.         252.         249.         209.
 191.         207.         215.         216.         217.
 218.         220.         229.         254.         257.
 264.         269.         293.         297.         299.
 307.         332.         337.         338.         339.
 340.         342.         346.         348.         353.
 357.         373.         379.         382.         383.
 387.         388.         390.         392.         393.
 407.         409.         424.         432.         447.
 452.         466.         468.         474.         477.
 520.         555.         597.         258.         267.
 270.         271.         273.         274.         275.
 279.         283.         287.         292.         294.
 298.         300.         301.         304.         305.
 311.         315.         317.         320.         325.
 330.         331.         333.         334.         335.
 336.         345.         350.         356.         359.
 362.         365.         367.         368.         370.
 371.         374.         376.         377.         380.
 381.         385.         389.         395.         397.
 400.         401.         402.         405.         410.
 414.         415.         418.         421.         423.
 433.         434.         435.         437.         440.
 442.         443.         449.         455.         461.
 464.         465.         483.         487.         490.
 491.         492.         494.         497.         505.
 508.         511.         513.         518.         521.
 525.         530.         533.         534.         536.
 538.         541.         547.         550.         551.
 552.         560.         562.         567.         573.
 574.         577.         582.         583.         584.
 589.         600.         604.         612.         619.
 621.         630.         631.         633.         635.
 640.         641.         644.         645.         655.
 661.         667.         668.         691.         701.
 703.         708.         750.         753.         760.
 778.         854.         981.         359.26851852]
['Premium' 'Ekonomiczna' 'Średnia']
sklep opon
[ 376.99  310.    225.49  299.    239.    322.    335.    244.99  227.
  385.    320.    460.    289.    224.99  399.    360.    343.99  345.
  329.13  402.99  450.99  370.    435.    277.99  355.    289.99  347.
  467.    430.    269.24  444.94  446.98  355.5   301.28  245.    416.99
  302.98  374.84  312.65  319.57  380.93  341.99  386.64  325.67  197.09
  484.81  534.43  257.99  476.49  491.19  522.72  334.38  348.59  285.99
  502.64  728.52  250.53  587.41  312.43  228.02  547.99  542.76  229.99
  505.27  213.76  617.99  322.23  431.6   572.99  221.58  437.02  357.19
  221.76  425.55  333.09  322.95  234.99  487.73  415.08  533.32  457.02
  512.4   280.57  551.68  419.57  554.99  565.99  422.8   475.    391.99
  281.68  487.32  243.53  443.58  554.41  400.74  413.74  455.99  227.08
  524.88  367.19  496.3   330.12  418.19  613.27  200.82  238.12  532.8
  619.55  312.53  315.61  332.99  324.17  372.99  260.47  336.37  464.99
  779.81  436.31  653.93  552.43  484.95  485.08  634.11  335.82  384.24
  408.6   259.52  491.41  338.76  531.72  308.72  478.49 3240.55  368.93
  361.3   421.01  490.13  423.99  486.34  534.01  595.31  751.58  510.44
 1168.49  469.48 1135.74  631.1   307.12  328.16  506.27  222.99  238.99
  306.31  387.18  488.99 2317.73  258.99  674.31  305.77  518.16  559.06
  353.99  561.72  416.75  363.95  393.64  400.52  506.97  337.38  581.78
  507.88  389.65  565.75  314.19  278.63  349.06  458.78  404.6   545.99
  317.95  482.92  315.24 1393.4   238.68 1133.57  623.32  326.06  377.24
  306.96  770.43  338.24  421.2   536.31  981.48  436.58  563.93  694.24
  580.9   600.81  760.15  511.42  323.47  332.88  366.57  308.47  462.72
  289.8   360.81  831.46  447.65  508.39  538.31  380.47  401.76  645.34
  817.4   364.84  588.86  255.92  294.94  214.42  228.78  549.16  321.72
  453.48  412.66  691.27  522.25  861.56  943.12  324.3   468.05  386.02
  357.18  447.21  826.17  380.06  780.47  582.8   426.38  410.67  553.49
  239.84  336.89  370.07  415.32  607.41  411.47  525.14  555.77  467.39
  614.99 2721.67 1024.59  325.21  602.87  826.82  650.94  321.38  341.45
  312.9  1159.88  530.12  591.63  752.63  347.29  478.95  413.27  308.14
  417.64  327.42  240.3   527.16  359.89  618.31  576.74  477.5   634.39
  327.63  522.91  562.12  404.1   496.91  358.89  305.85  439.64  642.05
  502.25  563.99  353.12  760.14 3542.51 1181.35  468.36  442.32  370.13
  534.33 2496.76  550.19  314.87  344.82  411.32  576.36 1205.81  445.54
  285.84  385.42  813.    658.41  382.18  862.48  306.14  469.36  350.78
  579.05  319.67  358.86  698.62  351.15  997.45  621.17  272.    223.
  204.43  360.3   389.    449.    376.39  217.43  563.72  582.16  451.76
  446.21  493.51  375.72  469.09  479.08  564.2   427.41  255.27  495.54
  438.5   615.17  352.55  523.91  499.    554.4   324.63  499.45  274.82
  364.35  478.64  243.77  377.39  380.76  558.64  324.28 1059.57  340.47
  374.43  643.11  328.23]
['Premium' 'Średnia' 'Ekonomiczna']

### #3. Znalezienie, uzupełnienie i usunięcie duplikatów
- Funkcja do identyfikacji duplikatów na podstawie 'name', 'brand', 'model' i wypełniania brakujących danych
- Usuwa duplikaty na podstawie ilości uzupełnionych kolumn - zostawia wiersz z największą ilością uzupełnionych kolumn

In [9]:
def fill_missing_with_duplicates(df_param):
    # Krok 1: Znalezienie duplikatów
    duplicates = df_param[df_param.duplicated(subset=['name', 'brand', 'model'], keep=False)]
    
    # Krok 2: Iteracja po grupach duplikatów
    for idx, group in duplicates.groupby(['name', 'brand', 'model']):
        for col in df_param.columns:
            if group[col].isna().any():
                # Jeśli mamy wartości do wypełnienia, to szukamy pierwszej dostępnej wartości
                fill_value = group[col].dropna().iloc[0] if not group[col].dropna().empty else None
                if fill_value is not None:  # Tylko wypełniaj, jeśli fill_value nie jest None
                    df_param.loc[group.index, col] = df_param.loc[group.index, col].fillna(fill_value)

    # Krok 3: Dodanie kolumny pomocniczej 'non_nan_count', która liczy liczbę nie-NaN wierszy
    df_param['non_nan_count'] = df_param.notna().sum(axis=1)
    
    # Krok 4: Grupowanie po duplikatach i wybieranie wiersza z największą liczbą nie-NaN
    df_param = df_param.loc[df_param.groupby(['name', 'brand', 'model'])['non_nan_count'].idxmax()]

    # Krok 5: Usunięcie kolumny pomocniczej
    df_param.drop(columns=['non_nan_count'], inplace=True)
    
    return df_param

print("Przed usunięciem duplikatów")
print(df_oponeo.shape)
print(df_sklep_opon.shape)

df_oponeo = fill_missing_with_duplicates(df_oponeo)
df_sklep_opon = fill_missing_with_duplicates(df_sklep_opon)

print("Po usunięciu duplikatów")
print(df_oponeo.shape)
print(df_sklep_opon.shape)

Przed usunięciem duplikatów
(222, 14)
(406, 14)
Po usunięciu duplikatów
(208, 14)
(289, 14)

### #4. Usuwanie wierszy z brakującymi wartościami w istotnych kolumnach

In [11]:
df_oponeo.dropna(subset=['fuel_index', 'wet_grip_index', 'noise_index'], inplace=True)
df_sklep_opon.dropna(subset=['fuel_index', 'wet_grip_index', 'noise_index'], inplace=True)

df_oponeo.dropna(subset=['availability'], inplace=True)
df_sklep_opon.dropna(subset=['availability'], inplace=True)

print("Po usunięciu braków danych")
print(df_oponeo.shape)
print(df_sklep_opon.shape)

Po usunięciu braków danych
(203, 14)
(219, 14)

### #5. Zastąpienie brakujących wartości w user_rating na 0

In [13]:
df_oponeo['user_rating'] = df_oponeo['user_rating'].fillna(0)
df_sklep_opon['user_rating'] = df_sklep_opon['user_rating'].fillna(0)

### #6. Wyświetlenie danych po czyszczeniu i zapisanie do plików CSV

In [24]:
print("sklep opon")
print("typy danych w kolumnach")
print(df_sklep_opon.dtypes)
print("unikalne wartości w kolumnach")
for column in df_sklep_opon.columns:
    if column not in ["name", "brand", "model"]:
        print(column, df_sklep_opon[column].unique())
display(df_sklep_opon)

print("oponeo")
print("typy danych w kolumnach")
print(df_oponeo.dtypes)
print("unikalne wartości w kolumnach")
for column in df_oponeo.columns:
    if column not in ["name", "brand", "model"]:
        print(column, df_oponeo[column].unique())
display(df_oponeo)

df_oponeo.to_csv("data/miniprojekt/oponeo_cleaned.csv", index=False)
df_sklep_opon.to_csv("data/miniprojekt/sklep_opon_cleaned.csv", index=False)

sklep opon
typy danych w kolumnach
name                object
brand               object
model               object
size              category
load_index        category
speed_index       category
fuel_index        category
wet_grip_index    category
noise_index       category
noise_level          Int64
class             category
user_rating        float32
price              float32
availability      category
dtype: object
unikalne wartości w kolumnach
size ['205/55 R16']
Categories (1, object): ['205/55 R16']
load_index [91, 94]
Categories (2, int64): [91, 94]
speed_index ['H', 'T', 'V', 'R']
Categories (4, object): ['H', 'R', 'T', 'V']
fuel_index ['D', 'C', 'E', 'B']
Categories (4, object): ['B', 'C', 'D', 'E']
wet_grip_index ['B', 'A', 'C', 'E', 'D']
Categories (5, object): ['A', 'B', 'C', 'D', 'E']
noise_index ['A', 'B', 'C']
Categories (3, object): ['A', 'B', 'C']
noise_level <IntegerArray>
[68, 69, 71, 70, 72, 67]
Length: 6, dtype: Int64
class ['Premium', 'Średnia', 'Ekonomiczna']
Categories (3, object): ['Ekonomiczna', 'Premium', 'Średnia']
user_rating [5.5 5.7 5.4 5.  5.3 4.6 5.2 5.6 0.  5.1 4.4 4.9 4.7 4.2 1.  4.5 2.5 4.3
 4.8 2.3 6. ]
price [ 728.52 1168.49  826.82  460.    551.68  444.94  587.41  496.3   450.99
  469.36  617.99  813.    653.93  348.59  347.    370.07  482.92  462.72
  430.    576.74  475.    484.81  613.27  307.12  225.49  442.32  315.61
  380.47  563.99  367.19  437.02  511.42  447.65  508.39  389.65  301.28
  512.4   355.    399.    554.41  384.24  228.78  239.    299.    522.25
  408.6   326.06  634.39  312.43  524.88  229.99  234.99  338.24  341.99
  343.99  372.99  391.99  374.84  487.32  415.08  200.82  322.95  312.65
  322.23  294.94  581.78  330.12  553.49  534.43  658.41  302.98  289.
  468.05  413.74  278.63  250.53  238.12  404.6   260.47  507.88  506.27
  419.57  445.54  325.67  431.6   439.64  315.24  324.3   312.53  411.32
  228.02 2317.73  545.99  485.08  224.99  382.18  486.34  413.27  510.44
  561.72  244.99  358.86  491.19  257.99  393.64  436.31  359.89  285.99
  370.13  321.72  335.    385.    360.    435.    455.99  221.58  634.11
 2496.76  779.81  505.27  446.98  565.99  674.31  542.76  531.72  770.43
  533.32 1205.81  222.99  238.99  401.76  436.58  245.    478.95  552.43
 1135.74  477.5   496.91  469.48  538.31  364.84 3542.51  588.86  336.37
  502.25  400.74  197.09  214.42  360.81  338.76  366.57  361.3   631.1
  751.58  289.8   333.09  487.73  335.82  310.    319.57  565.75  289.99
  277.99  380.93  334.38  221.76  363.95  328.16  358.89  325.21  760.15
  572.99 1024.59  402.99  522.72  488.99  534.01  591.63  780.47 1393.4
  416.99  322.    370.    476.49  621.17  595.31  467.    547.99  698.62
  345.    443.58  530.12  416.75  336.89  623.32  320.    353.99  425.55
  645.34  239.84  329.13  332.99  421.01  484.95  213.76  376.99  355.5
  518.16  227.    464.99  559.06  576.36  981.48]
availability ['full', 'medium', 'low', 'last']
Categories (4, object): ['full', 'last', 'low', 'medium']

,name,brand,model,size,load_index,speed_index,fuel_index,wet_grip_index,noise_index,noise_level,class,user_rating,price,availability
0,Alpin 5 205/55 R16 91 H,Michelin,Alpin 5,205/55 R16,91,H,D,B,A,68,Premium,5.5,728.520020,full
1,Alpin 6 205/55 R16 91 H,Michelin,Alpin 6,205/55 R16,91,H,C,B,A,69,Premium,5.7,1168.489990,medium
2,Alpin 6 205/55 R16 91 T,Michelin,Alpin 6,205/55 R16,91,T,C,B,A,69,Premium,5.7,826.820007,full
3,Alpin 7 205/55 R16 91 H,Michelin,Alpin 7,205/55 R16,91,H,C,B,B,71,Premium,5.4,460.000000,full
4,Alpin 7 205/55 R16 91 T,Michelin,Alpin 7,205/55 R16,91,T,C,B,B,71,Premium,5.4,460.000000,full
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,Z507 205/55 R16 91 V,Goodride,Z507,205/55 R16,91,V,C,C,B,72,Ekonomiczna,5.1,227.000000,full
215,g-Force Winter 2 205/55 R16 91 H,Bfgoodrich,g-Force Winter 2,205/55 R16,91,H,D,B,A,69,Średnia,5.2,464.989990,full
216,g-Force Winter 2 205/55 R16 91 T,Bfgoodrich,g-Force Winter 2,205/55 R16,91,T,D,B,A,69,Średnia,5.2,559.059998,full
217,g-Force Winter 2 205/55 R16 94 H,Bfgoodrich,g-Force Winter 2,205/55 R16,94,H,D,B,A,69,Średnia,5.2,576.359985,medium
218,g-Force Winter 2 205/55 R16 94 V,Bfgoodrich,g-Force Winter 2,205/55 R16,94,V,D,B,A,68,Średnia,5.2,981.479980,full

# Eksploracyjna Analiza danych

- Opcjonalne ładowanie oczyszczonych danych z plików CSV jeżeli nie chcemy ponownie scrapować danych

In [7]:
df_oponeo = pd.read_csv("data/miniprojekt/oponeo_cleaned.csv", delimiter=",")
df_sklep_opon = pd.read_csv("data/miniprojekt/sklep_opon_cleaned.csv", delimiter=",")
update_column_types()

df_oponeo['retailer'] = 'Oponeo'
df_sklep_opon['retailer'] = 'Sklep opon'
df = pd.concat([df_oponeo, df_sklep_opon], ignore_index=True)

### #1. Średnia, mediana, min i max cen opon w każdym sklepie

In [8]:
price_stats = df.groupby('retailer')['price'].agg(['mean', 'median', 'min', 'max'])
price_stats

                  mean      median         min         max
retailer
Oponeo      426.227905  400.000000  191.000000   854.00000
Sklep opon  480.524902  419.570007  197.089996  3542.51001

## #2. Średnia cena opon w zależności od marki i sklepu

In [9]:
brand_price_stats = df.groupby(['retailer', 'brand'])['price'].mean().unstack()
brand_price_stats

brand,Aplus,Apollo,Arivo,Austone,Autogreen,BFGoodrich,Barum,Bfgoodrich,Bridgestone,Ceat,...,Triangle,Tristar,Uniroyal,Viking,Vredestein,West Lake,Windforce,Yokohama,ZMax,Zeetex
retailer,,,,,,,,,,,,,,,,,,,,,
Oponeo,320.0,376.333344,267.000000,380.000000,NaN,582.0,519.400024,NaN,576.090881,265.50000,...,279.000000,370.0,443.666656,479.000000,445.166656,341.0,421.000000,478.75000,NaN,264.0
Sklep opon,NaN,NaN,292.855011,303.584991,321.720001,NaN,484.019989,645.472473,566.739990,400.73999,...,221.580002,NaN,415.672485,553.960022,424.725983,NaN,383.787506,387.14502,360.809998,NaN

### #3. Średnia cena opon w zależności od klasy i sklepu

In [13]:
class_price_stats = df.groupby(['retailer', 'class'], observed=False)['price'].mean().unstack()
class_price_stats

class       Ekonomiczna     Premium     Średnia
retailer
Oponeo       358.990112  536.123230  433.372101
Sklep opon   324.129700  655.906372  434.269318

### #4. Średnia ocena użytkownika w każdym sklepie

In [15]:
rating_stats = df.groupby('retailer')['user_rating'].mean()
rating_stats

retailer
Oponeo        3.966010
Sklep opon    4.489041
Name: user_rating, dtype: float32

### #5. Liczba opon w każdej klasie efektywności w obu sklepach

In [17]:
class_distribution = df.groupby(['retailer', 'class'], observed=False).size().unstack()
class_distribution

class       Ekonomiczna  Premium  Średnia
retailer
Oponeo              101       59       43
Sklep opon           67       79       73

### #6. Średnia ceny opon w zależności od:
 - sklepu oraz indeksów: paliwowego, przyczepności i hałasu
 - sklepu oraz nośności
 - sklepu oraz indeksu prędkości

In [63]:
pivot_price_indices = df.pivot_table(
    values='price',
    index='retailer',
    columns=['fuel_index', 'wet_grip_index', 'noise_index'],
    aggfunc='mean',
    observed=False
)
display(pivot_price_indices)

pivot_price_speed_load = df.pivot_table(
    values='price',
    index='retailer',
    columns='speed_index',
    aggfunc='mean',
    observed=False
)
display(pivot_price_speed_load)

pivot_price_load = df.pivot_table(
    values='price',
    index='retailer',
    columns='load_index',
    aggfunc='mean',
    observed=False
)
display(pivot_price_load)

fuel_index          B                                   C              \
wet_grip_index      B           C           D           A           B
noise_index         A           B           A           B           A
retailer
Oponeo          577.0  427.000000         NaN  623.000000  502.875000
Sklep opon      435.0  389.221436  634.390015  601.054016  569.471558

fuel_index                                                   ...           D  \
wet_grip_index                  C                         D  ...           C
noise_index              B      A           B      C      A  ...           C
retailer                                                     ...
Oponeo          465.239990  379.0  381.805542  300.0  283.0  ...         NaN
Sklep opon      473.080536    NaN  389.586182    NaN    NaN  ...  807.344971

fuel_index                                      E                         \
wet_grip_index          D           E           B                      C
noise_index             B           B           A          B           B
retailer
Oponeo          309.37500         NaN  359.268524  421.00000  410.571442
Sklep opon      812.08252  358.859985         NaN  378.63501  448.428345

fuel_index                                         F
wet_grip_index           D           E      F      C
noise_index              B           B      B      B
retailer
Oponeo          405.333344  393.000000  423.0  363.5
Sklep opon             NaN  581.780029    NaN    NaN

[2 rows x 27 columns]

speed_index           H           R           T           V
retailer
Oponeo       425.361481         NaN  421.410248  434.527771
Sklep opon   439.631470  634.390015  531.429199  546.580505

load_index          91          94
retailer
Oponeo      412.209076  457.380951
Sklep opon  465.595795  508.056519

### #7. Porównanie:
 - cen opon w obu sklepach dla tych samych modeli
  - dostępności opon w obu sklepach dla tych samych modeli

In [64]:
unique_df_price = df.groupby(['brand', 'model', 'retailer'], as_index=False)['price'].min()

df_oponeo = unique_df_price[unique_df_price['retailer'] == 'Oponeo'][['brand', 'model', 'price']].rename(columns={'price': 'Oponeo'})
df_sklep_opon = unique_df_price[unique_df_price['retailer'] == 'Sklep opon'][['brand', 'model', 'price']].rename(columns={'price': 'Sklep opon'})

price_comparison_df = pd.merge(df_oponeo, df_sklep_opon, on=['brand', 'model'], how='inner')

price_comparison_df['cheaper_in'] = price_comparison_df.apply(
    lambda row: 'Oponeo' if row['Oponeo'] < row['Sklep opon'] else 'Sklep opon' if row['Oponeo'] > row['Sklep opon'] else 'Same price',
    axis=1
)

display(price_comparison_df)

unique_df_availability = df.groupby(['brand', 'model', 'retailer'], as_index=False)['availability'].max()

df_oponeo = unique_df_availability[unique_df_availability['retailer'] == 'Oponeo'][['brand', 'model', 'availability']].rename(columns={'availability': 'Oponeo'})
df_sklep_opon = unique_df_availability[unique_df_availability['retailer'] == 'Sklep opon'][['brand', 'model', 'availability']].rename(columns={'availability': 'Sklep opon'})

availability_comparison_df = pd.merge(df_oponeo, df_sklep_opon, on=['brand', 'model'], how='inner')

availability_comparison_df['more_available_in'] = availability_comparison_df.apply(
    lambda row: 'Oponeo' if row['Oponeo'] > row['Sklep opon'] else 'Sklep opon' if row['Oponeo'] < row['Sklep opon'] else 'Taka sama dostępność',
    axis=1
)

display(availability_comparison_df)

           brand                     model  Oponeo  Sklep opon  cheaper_in
0        Austone                     SP901   380.0  224.990005  Sklep opon
1          Barum                 Polaris 5   655.0  534.429993  Sklep opon
2          Barum                 Polaris 6   367.0  289.000000  Sklep opon
3    Bridgestone                 Blizzak 6   468.0  444.940002  Sklep opon
4    Bridgestone             Blizzak LM001   465.0  587.409973      Oponeo
5    Bridgestone         Blizzak LM001 EVO   491.0  496.299988      Oponeo
6    Bridgestone             Blizzak LM005   459.0  450.989990  Sklep opon
7    Bridgestone  Blizzak LM005 DriveGuard   631.0  653.929993      Oponeo
8    Continental    WinterContact TS 860 S   582.0  595.309998      Oponeo
9    Continental      WinterContact TS 870   464.0  460.000000  Sklep opon
10        Cooper         Discoverer Winter   513.0  380.470001  Sklep opon
11        Dunlop        SP Winter Sport 4D   560.0  485.079987  Sklep opon
12        Dunlop            Winter Sport 5   409.0  402.989990  Sklep opon
13        Dębica                   Frigo 2   252.0  239.000000  Sklep opon
14        Dębica                 Frigo HP2   311.0  299.000000  Sklep opon
15        Falken           Eurowinter HS01   435.0  355.000000  Sklep opon
16        Falken           Eurowinter HS02   582.0  399.000000  Sklep opon
17     Firestone              Winterhawk 4   342.0  329.130005  Sklep opon
18       Fortune                   FSR-901   258.0  228.779999  Sklep opon
19         Fulda      Kristall Control HP2   461.0  374.839996  Sklep opon
20      Goodride                     SW608   333.0  244.990005  Sklep opon
21      Goodride                     SW618   423.0  358.859985  Sklep opon
22       Hankook    Winter i*cept RS3 W462   346.0  322.000000  Sklep opon
23        Kleber               Krisalp HP3   339.0  341.989990      Oponeo
24      Kormoran                      Snow   249.0  257.989990      Oponeo
25      Linglong       Green-Max Winter HP   325.0  326.059998      Oponeo
26       Matador             MP93 Nordicca   350.0  312.649994  Sklep opon
27      Michelin                   Alpin 7   466.0  460.000000  Sklep opon
28         Nexen       Winguard Snow'G WH2   293.0  310.000000      Oponeo
29         Nexen          Winguard Sport 2   359.0  334.380005  Sklep opon
30  Nokian Tyres               Snowproof 1   338.0  335.000000  Sklep opon
31  Nokian Tyres               Snowproof 2   397.0  360.000000  Sklep opon
32       Pirelli          Cinturato Winter   490.0  484.809998  Sklep opon
33       Pirelli        Cinturato Winter 2   424.0  430.000000      Oponeo
34       Pirelli            Powergy Winter   387.0  413.739990      Oponeo
35         Riken                      Snow   385.0  359.890015  Sklep opon
36       Rotalla                      S210   317.0  238.119995  Sklep opon
37          Sava                Eskimo S3+   368.0  301.279999  Sklep opon
38          Toyo              Observe S944   402.0  330.119995  Sklep opon
39       Tracmax                      S210   401.0  260.470001  Sklep opon
40      Uniroyal              WinterExpert   388.0  343.989990  Sklep opon
41    Vredestein                Snowtrac 5   466.0  455.989990  Sklep opon
42    Vredestein                   Wintrac   379.0  355.500000  Sklep opon

,brand,model,Oponeo,Sklep opon,more_available_in
0,Austone,SP901,full,medium,Sklep opon
1,Barum,Polaris 5,full,medium,Sklep opon
2,Barum,Polaris 6,medium,full,Oponeo
3,Bridgestone,Blizzak 6,medium,medium,Taka sama dostępność
4,Bridgestone,Blizzak LM001,full,low,Sklep opon
5,Bridgestone,Blizzak LM001 EVO,full,full,Taka sama dostępność
6,Bridgestone,Blizzak LM005,medium,medium,Taka sama dostępność
7,Bridgestone,Blizzak LM005 DriveGuard,medium,full,Oponeo
8,Continental,WinterContact TS 860 S,full,full,Taka sama dostępność
9,Continental,WinterContact TS 870,medium,medium,Taka sama dostępność
10,Cooper,Discoverer Winter,medium,medium,Taka sama dostępność
11,Dunlop,SP Winter Sport 4D,medium,medium,Taka sama dostępność
12,Dunlop,Winter Sport 5,full,full,Taka sama dostępność
13,Dębica,Frigo 2,full,full,Taka sama dostępność
14,Dębica,Frigo HP2,full,full,Taka sama dostępność
15,Falken,Eurowinter HS01,full,full,Taka sama dostępność
16,Falken,Eurowinter HS02,full,low,Sklep opon
17,Firestone,Winterhawk 4,medium,medium,Taka sama dostępność
18,Fortune,FSR-901,full,full,Taka sama dostępność
19,Fulda,Kristall Control HP2,full,medium,Sklep opon
20,Goodride,SW608,full,full,Taka sama dostępność
21,Goodride,SW618,full,low,Sklep opon
22,Hankook,Winter i*cept RS3 W462,full,full,Taka sama dostępność
23,Kleber,Krisalp HP3,full,full,Taka sama dostępność
24,Kormoran,Snow,full,full,Taka sama dostępność
25,Linglong,Green-Max Winter HP,full,full,Taka sama dostępność
26,Matador,MP93 Nordicca,full,medium,Sklep opon
27,Michelin,Alpin 7,full,full,Taka sama dostępność
28,Nexen,Winguard Snow'G WH2,full,low,Sklep opon
29,Nexen,Winguard Sport 2,full,full,Taka sama dostępność
30,Nokian Tyres,Snowproof 1,full,full,Taka sama dostępność
31,Nokian Tyres,Snowproof 2,medium,medium,Taka sama dostępność
32,Pirelli,Cinturato Winter,full,full,Taka sama dostępność
33,Pirelli,Cinturato Winter 2,full,medium,Sklep opon
34,Pirelli,Powergy Winter,full,full,Taka sama dostępność
35,Riken,Snow,full,medium,Sklep opon
36,Rotalla,S210,full,full,Taka sama dostępność
37,Sava,Eskimo S3+,full,full,Taka sama dostępność
38,Toyo,Observe S944,low,low,Taka sama dostępność
39,Tracmax,S210,full,full,Taka sama dostępność
40,Uniroyal,WinterExpert,medium,medium,Taka sama dostępność
41,Vredestein,Snowtrac 5,full,full,Taka sama dostępność
42,Vredestein,Wintrac,full,full,Taka sama dostępność