In [1]:
import pandas as pd
import re

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.common.exceptions import NoSuchElementException

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

In [6]:
download_service = Service()
driver = webdriver.Chrome(service=download_service)

#driver.get("https://www.sklepopon.com/szukaj-opony?sezon=zimowe&rozmiar=205/55R16&ofs=0")
# driver.get("https://www.oponeo.pl/wybierz-opony/s=1/zimowe/t=1/osobowe/r=1/205-55-r16")
# https://www.oponeo.pl/wybierz-opony/s=1/zimowe/t=1/osobowe/r=1/205-55-r16#&&/wEXDAULcGNrX1ByTFNST0YFA+KUpAUVcGNrX0xzdFNTb3J0UGFyYW1ldGVyBQIzNwUOcGNrX1RyTFNTc25JZHMFATIFCXBja19UckxTUgUD4pSkBQdwY2tfQ1BnBQEyBQpwY2tfVHJMU1BUBQQxMTAwBQhwY2tfSU9GUAUCNjgFDHBja19UckxTU0lkcwUDMjUyBQtwY2tfVHJJT25seQUD4pSkBQpwY2tfVHJMU1BGBQMxOTEFDXBja19UckxTVFRJZHMFATIFFXBja19UckxTU29ydERpcmVjdGlvbgUBMtD9aDKZ+9GYcVUKukEj6XnJhNql
#https://www.oponeo.pl/wybierz-opony/s=1/zimowe/t=1/osobowe/r=1/205-55-r16#&&/wEXDAULcGNrX1ByTFNST0YFA+KUpAUVcGNrX0xzdFNTb3J0UGFyYW1ldGVyBQIzNwUOcGNrX1RyTFNTc25JZHMFATIFCXBja19UckxTUgUD4pSkBQdwY2tfQ1BnBQEzBQpwY2tfVHJMU1BUBQQxMTAwBQhwY2tfSU9GUAUCNjgFDHBja19UckxTU0lkcwUDMjUyBQtwY2tfVHJJT25seQUD4pSkBQpwY2tfVHJMU1BGBQMxOTEFDXBja19UckxTVFRJZHMFATIFFXBja19UckxTU29ydERpcmVjdGlvbgUBMlWnHdgz3AaHVlQ3gBlfXfTWethI

sklep_opon_base_url = "https://www.sklepopon.com/szukaj-opony?sezon=zimowe&rozmiar=205/55R16&ofs="
oponeo_base_url = "https://www.oponeo.pl/wybierz-opony/s=1/zimowe/t=1/osobowe/r=1/205-55-r16"

In [3]:

import time

def hide_sklep_opon_popups():
    # Obsługa przycisku akceptacji ciasteczek
    try:
        btn_cookie = driver.find_element(By.CSS_SELECTOR, "#klaro > div > div > div > div > div > button")
        btn_cookie.click()
        print("Przycisk akceptacji ciasteczek został kliknięty.")
    except NoSuchElementException:
        print("Przycisk akceptacji ciasteczek nie został znaleziony.")
    except Exception as exception:
        print("Nie udało się kliknąć przycisku akceptacji ciasteczek:", exception)
    
    # Obsługa okna powiadomień w shadow DOM
    try:
        driver.execute_script("""
            const shadowHost = document.querySelector("body > div.gr-visual-prompt");
            if (shadowHost) {
                const shadowRoot = shadowHost.shadowRoot;
                const closeButton = shadowRoot.querySelector("div > div:nth-child(2) > button:nth-child(1)");
                if (closeButton) {
                    closeButton.click();
                    console.log("Okienko powiadomień zostało zamknięte.");
                } else {
                    console.log("Nie znaleziono przycisku zamknięcia powiadomień.");
                }
            } else {
                console.log("Okno powiadomień nie zostało znalezione.");
            }
        """)
    except Exception as exception:
        print("Nie udało się zamknąć okienka powiadomień:", exception)

def close_oponeo_privacy_popup():
    try:
        # Wyszukanie elementu przycisku "Odrzuć wszystkie"
        reject_button = driver.find_element(By.CSS_SELECTOR, "#consentsBar > div.buttonsContainer.container > div > span.reject")
        reject_button.click()
        print("Okienko prywatności zostało zamknięte.")
    except NoSuchElementException:
        print("Okienko prywatności nie jest widoczne lub zostało już zamknięte.")
    except Exception as e:
        print("Wystąpił błąd podczas zamykania okienka prywatności:", e)

In [5]:


def load_sklep_opon_tyre_data():
    try:
        # Znalezienie wszystkich elementów opon w sekcji listing-products-element
        opony_elements = driver.find_elements(By.CSS_SELECTOR, 'div[data-c-name="listing-products-element"]')
        
        # Iteracja przez każdy element opony
        for opona_element in opony_elements:
            # Słownik do przechowywania danych jednej opony
            opona_data = {}
    
            # Pobranie danych do słownika
            opona_data['name'] = opona_element.get_attribute('data-ee-product-properties').split(";")[0].split(":")[1]
            opona_data['brand'] = opona_element.get_attribute('data-ee-product-properties').split(";")[4].split(":")[1]
            opona_data['model'] = opona_element.get_attribute('data-ee-product-properties').split(";")[6].split(":")[1]
            opona_data['size'] = opona_element.get_attribute('data-ee-product-properties').split(";")[5].split(":")[1]
            
            # Znalezienie indeksu nośności i indeksu prędkości
            try:
                load_index = opona_element.find_element(By.CSS_SELECTOR, 'li[data-attribute-code="li"]').text
                speed_index = opona_element.find_element(By.CSS_SELECTOR, 'li[data-attribute-code="si"]').text
                opona_data['load_index'] = load_index
                opona_data['speed_index'] = speed_index
            except NoSuchElementException:
                opona_data['load_index'] = None
                opona_data['speed_index'] = None
            
            # Pobieranie szczegółowych informacji o etykiecie
            etykieta_elements = opona_element.find_elements(By.CSS_SELECTOR, 'span.icon-fuel-new ~ span, span.icon-rain-new ~ span, span.icon-speaker-new ~ span')
            opona_data['fuel_index'] = etykieta_elements[0].text if len(etykieta_elements) > 0 else None
            opona_data['wet_grip_index'] = etykieta_elements[1].text if len(etykieta_elements) > 1 else None
            opona_data['noise_index'] = etykieta_elements[2].text.split(" ")[0] if len(etykieta_elements) > 2 else None
            
            # Pobieranie poziomu hałasu, uwzględniając wewnętrzny <span> z dB
            try:
                noise_level_elements = opona_element.find_elements(By.CSS_SELECTOR, "span.self-center.tracking-tighter.sm\\:tracking-normal")
                for noise_level_element in noise_level_elements:
                    text = noise_level_element.text
                    match = re.search(r'\d+', text)
                    if match:
                        noise_level = int(match.group())
                    else:
                        noise_level = None
                    opona_data['noise_level'] = noise_level
            except (NoSuchElementException, IndexError):
                opona_data['noise_level'] = None
            
            class_mapping = {
                "Premium": "Premium",
                "Średnia": "Średnia",
                "Średniej": "Średnia",
                "Ekonomiczna": "Ekonomiczna",
                "Ekonomicznej": "Ekonomiczna"
            }
            try:
                tyre_class_element = opona_element.find_element(By.XPATH, ".//*[contains(translate(text(), 'ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'abcdefghijklmnopqrstuvwxyz'), 'klas')]")
                # Dopasuj i wyczyść tekst
                opona_class = tyre_class_element.text.lower().replace("w klasie ", "").replace("klasa ", "").strip().capitalize()
                opona_data['class'] = class_mapping.get(opona_class, opona_class)
            except NoSuchElementException:
                opona_data['class'] = None
            
            # Pobieranie oceny użytkownika (tekstowa wartość obok gwiazdek)
            try:
                user_rating_element = opona_element.find_element(By.XPATH, ".//li[contains(@class, 'xl:hidden')]//span[contains(@class, 'ml-1')]")
                opona_data['user_rating'] = float(user_rating_element.text.replace(",", "."))
            except NoSuchElementException:
                opona_data['user_rating'] = None
            
            opona_data['price'] = float(opona_element.get_attribute('data-ee-product-properties').split(";")[3].split(":")[1])
            
            # Dodajemy dane opony do listy
            sklep_opon_tyres_data.append(opona_data)
    finally:
        pass

sklep_opon_tyres_data = []
offset = 0

while True:
    url = f"{sklep_opon_base_url}{offset}"
    driver.get(url)
    time.sleep(4)
    
    if offset == 0:
        hide_sklep_opon_popups()
    
    load_sklep_opon_tyre_data()
    
    offset += 20
    # Warunek zatrzymania przy pustej stronie
    if len(driver.find_elements(By.CSS_SELECTOR, 'div[data-c-name="listing-products-element"]')) == 0:
        print("Brak nowych danych. Koniec paginacji.")
        break
# Zamknięcie WebDrivera
driver.quit()

# Wydrukowanie listy wszystkich danych o oponach
df = pd.DataFrame(sklep_opon_tyres_data)
display(df)

Przycisk akceptacji ciasteczek nie został znaleziony.

,name,brand,model,size,load_index,speed_index,fuel_index,wet_grip_index,noise_index,noise_level,class,user_rating,price
0,Wintrac 205/55 R16 91 H,Vredestein,Wintrac,205/55 R16,91,H,C,B,B,70,Premium,5.4,376.99
1,Winguard Snow'G WH2 205/55 R16 91 H,Nexen,Winguard Snow'G WH2,205/55 R16,91,H,D,C,B,70,Średnia,5.3,310.00
2,SP901 205/55 R16 91 H,Austone,SP901,205/55 R16,91,H,D,D,B,72,Ekonomiczna,5.1,224.99
3,Frigo HP2 205/55 R16 91 H,Dębica,Frigo HP2,205/55 R16,91,H,C,C,B,72,Ekonomiczna,5.2,283.00
4,Frigo 2 205/55 R16 91 T,Dębica,Frigo 2,205/55 R16,91,T,C,C,B,71,Ekonomiczna,5.1,239.00
5,Winter i*cept RS3 W462 205/55 R16 91 T,Hankook,Winter i*cept RS3 W462,205/55 R16,91,T,C,B,B,72,Premium,5.3,322.00
6,Snowproof 1 205/55 R16 91 H,Nokian Tyres,Snowproof 1,205/55 R16,91,H,C,B,B,70,Premium,5.4,335.00
7,SW608 205/55 R16 91 H,Goodride,SW608,205/55 R16,91,H,C,C,B,72,Ekonomiczna,5.1,244.99
8,Snowproof 2 205/55 R16 91 H,Nokian Tyres,Snowproof 2,205/55 R16,91,H,C,B,A,69,Premium,5.6,385.00
9,Z507 205/55 R16 91 V,Goodride,Z507,205/55 R16,91,V,C,C,B,72,Ekonomiczna,5.1,227.00
10,Wintercraft WP52 205/55 R16 91 H,Kumho,Wintercraft WP52,205/55 R16,91,H,C,B,B,72,Średnia,5.1,320.00
11,WinterContact TS 870 205/55 R16 91 H,Continental,WinterContact TS 870,205/55 R16,91,H,C,B,B,70,Premium,5.6,460.00
12,Polaris 6 205/55 R16 91 T,Barum,Polaris 6,205/55 R16,91,T,B,C,B,72,Ekonomiczna,5.0,289.00
13,Snowproof 2 205/55 R16 91 T,Nokian Tyres,Snowproof 2,205/55 R16,91,T,C,B,A,69,Premium,5.6,360.00
14,Eurowinter HS02 205/55 R16 91 H,Falken,Eurowinter HS02,205/55 R16,91,H,D,B,A,69,Średnia,5.4,399.00
15,WinterExpert 205/55 R16 91 T,Uniroyal,WinterExpert,205/55 R16,91,T,C,B,B,71,Średnia,5.4,343.99
16,WinterExpert 205/55 R16 91 H,Uniroyal,WinterExpert,205/55 R16,91,H,C,B,B,71,Średnia,5.4,345.00
17,Winter Sport 5 205/55 R16 91 H,Dunlop,Winter Sport 5,205/55 R16,91,H,C,B,B,71,Premium,5.4,402.99
18,Blizzak LM005 205/55 R16 91 H,Bridgestone,Blizzak LM005,205/55 R16,91,H,C,A,B,71,Premium,5.5,450.99
19,Winterhawk 4 205/55 R16 91 H,Firestone,Winterhawk 4,205/55 R16,91,H,C,B,B,71,Średnia,5.3,329.13
20,Winter i*cept RS3 W462 205/55 R16 94 H,Hankook,Winter i*cept RS3 W462,205/55 R16,94,H,C,B,B,72,Premium,5.3,370.00
21,Winguard Snow'G3 WH21 205/55 R16 91 T,Nexen,Winguard Snow'G3 WH21,205/55 R16,91,T,D,B,B,72,Średnia,5.2,277.99
22,Snowproof 2 205/55 R16 94 H,Nokian Tyres,Snowproof 2,205/55 R16,94,H,B,B,A,69,Premium,5.6,389.00

In [31]:
def load_oponeo_tyre_data(driver):
    """
    Pobiera dane opon z bieżącej strony i zwraca je jako listę słowników.
    """
    tires_data = []
    products = driver.find_elements(By.CLASS_NAME, "product")
    
    for product in products:
        try:
            # Wyciąganie linku i nazwy produktu z `productName`, jeśli dostępne
            try:
                link_element = product.find_element(By.CSS_SELECTOR, ".productName a")
                nazwa = link_element.get_attribute("title")
            except NoSuchElementException:
                # Jeśli nie znaleziono elementu `a` wewnątrz `productName`
                nazwa = product.find_element(By.CLASS_NAME, "productName").text

            noise = product.find_element(By.CSS_SELECTOR, ".icon-noise em").text
            match = re.search(r'\d+', noise)
            if match:
                noise_level = int(match.group())
            else:
                noise_level = int(product.find_element(By.CSS_SELECTOR, ".icon-noise em").text.split()[1].replace("dB", "").strip())
             
             # Wyciąganie pozostałych szczegółów z dodaną walidacją dla `wet_grip_index`
            noise_index = product.find_element(By.CSS_SELECTOR, ".icon-noise em").text.split()[0] 
            noise_index_text = noise_index if noise_index in {"A", "B", "C", "D", "E", "F"} and len(noise_index) == 1 else None   
                
             # Pobieranie oceny użytkownika (lub None jeśli brak oceny)
            try:
                user_rating = product.find_element(By.CSS_SELECTOR, ".productRating .note").text
            except NoSuchElementException:
                user_rating = None
                
            # Wyciąganie pozostałych szczegółów
            tire_info = {
                "name": nazwa,
                "brand": product.find_element(By.CLASS_NAME, "producerName").text,
                "model": product.find_element(By.CLASS_NAME, "modelName").text,
                "size": product.find_element(By.CLASS_NAME, "modelSize").text,
                "load_index": product.find_element(By.XPATH, ".//span[@data-tp='TireLoadIndex']/em").text,
                "speed_index": product.find_element(By.XPATH, ".//span[@data-tp='TireSpeedIndex']/em").text,
                "fuel_index": product.find_element(By.CSS_SELECTOR, ".icon-fuel em").text,
                "wet_grip_index": product.find_element(By.CSS_SELECTOR, ".icon-rain em").text,
                "noise_index": noise_index_text,
                "noise_level": noise_level,
                "class": product.find_element(By.CLASS_NAME, "class").text.replace("KLASA ", "").capitalize(),
                "user_rating": user_rating,
                "price": product.find_element(By.CLASS_NAME, "priceValue").text,
            }
            
            # Dodajemy słownik do listy
            tires_data.append(tire_info)

        except NoSuchElementException:
            pass
            
    return tires_data

def go_to_next_page(web_driver, current_page_number):
    """
    Przechodzi do następnej strony na podstawie numeru strony. 
    Zwraca True, jeśli przejście się powiodło, w przeciwnym razie False.
    """
    try:
        # Wyszukiwanie przycisku z numerem strony
        print(f"finding page {current_page_number}")
        next_page_button = web_driver.find_element(By.ID, f"_ctPgrp_pi{current_page_number}i")
        print(f"page found {current_page_number}")
        next_page_button.click()
        # Opcjonalne odczekanie na załadowanie strony
        time.sleep(2)
        return True
    except NoSuchElementException:
        print(f"no page {current_page_number}")
        return False

# Kod główny do pobierania danych ze wszystkich stron
driver.get(oponeo_base_url)
close_oponeo_privacy_popup()

all_tires_data = []

page_number = 1
while True:
    # Pobranie danych z bieżącej strony
    tires_data = load_oponeo_tyre_data(driver)
    all_tires_data.extend(tires_data)
    
    # Przejście do następnej strony
    page_number += 1
    if not go_to_next_page(driver, page_number):
        break

# Wyświetlenie zebranych danych w DataFrame
df2 = pd.DataFrame(all_tires_data)
display(df2)

# Zamknięcie drivera
# driver.quit()

Okienko prywatności nie jest widoczne lub zostało już zamknięte.
finding page 2
page found 2
finding page 3
page found 3
finding page 4
page found 4
finding page 5
page found 5
finding page 6
page found 6
finding page 7
page found 7
finding page 8
page found 8
finding page 9
page found 9
finding page 10
no page 10

,name,brand,model,size,load_index,speed_index,fuel_index,wet_grip_index,noise_index,noise_level,class,user_rating,price
0,Bridgestone Blizzak LM005 205/55 R16 91 H,Bridgestone,Blizzak LM005,205/55 R16,91,H,C,A,B,71,Premium,"4,7",459
1,Michelin Alpin 7 205/55 R16 91 H,Michelin,Alpin 7,205/55 R16,91,H,C,B,B,71,Premium,"4,8",467
2,Dębica Frigo 2 205/55 R16 91 T,Dębica,Frigo 2,205/55 R16,91,T,C,C,B,71,Ekonomiczna,"4,2",252
3,Kormoran Snow 205/55 R16 91 H,Kormoran,Snow,205/55 R16,91,H,D,C,B,72,Ekonomiczna,"4,5",249
4,Firemax FM805+ 205/55 R16 91 H,Firemax,FM805+,205/55 R16,91,H,D,C,A,67,Ekonomiczna,"4,4",209
...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,Goodyear UG Performance 2 205/55 R16 91 H RUN ...,Goodyear,UG Performance 2,205/55 R16,91,H,D,C,B,72,Premium,"4,3",778
225,Bridgestone Blizzak LM005 205/55 R16 94 V XL,Bridgestone,Blizzak LM005,205/55 R16,94,V,C,A,B,71,Premium,"4,7",854
226,Barum Polaris 5 205/55 R16 94 V XL,Barum,Polaris 5,205/55 R16,94,V,C,C,B,72,Ekonomiczna,"4,4",854
227,Pirelli SottoZero Serie 3 205/55 R16 91 H RUN ...,Pirelli,SottoZero Serie 3,205/55 R16,91,H,D,B,B,72,Premium,"4,6",972
228,Michelin ALPIN 5 205/55 R16 91 H RUN ON FLAT,Michelin,ALPIN 5,205/55 R16,91,H,E,B,A,68,Premium,"4,6",1 100

In [32]:
# Weryfikacja poprawnych wartości w każdej kolumnie
print("sklep opon")
for column in df.columns:
    print(column, df[column].unique())

print("oponeo")
for column in df2.columns:
    print(column, df2[column].unique())

sklep opon
name ['Wintrac 205/55 R16 91 H' "Winguard Snow'G WH2 205/55 R16 91 H"
 'SP901 205/55 R16 91 H' 'Frigo HP2 205/55 R16 91 H'
 'Frigo 2 205/55 R16 91 T' 'Winter i*cept RS3 W462 205/55 R16 91 T'
 'Snowproof 1 205/55 R16 91 H' 'SW608 205/55 R16 91 H'
 'Snowproof 2 205/55 R16 91 H' 'Z507 205/55 R16 91 V'
 'Wintercraft WP52 205/55 R16 91 H' 'WinterContact TS 870 205/55 R16 91 H'
 'Polaris 6 205/55 R16 91 T' 'Snowproof 2 205/55 R16 91 T'
 'Eurowinter HS02 205/55 R16 91 H' 'WinterExpert 205/55 R16 91 T'
 'WinterExpert 205/55 R16 91 H' 'Winter Sport 5 205/55 R16 91 H'
 'Blizzak LM005 205/55 R16 91 H' 'Winterhawk 4 205/55 R16 91 H'
 'Winter i*cept RS3 W462 205/55 R16 94 H'
 "Winguard Snow'G3 WH21 205/55 R16 91 T" 'Snowproof 2 205/55 R16 94 H']
brand ['Vredestein' 'Nexen' 'Austone' 'Dębica' 'Hankook' 'Nokian Tyres'
 'Goodride' 'Kumho' 'Continental' 'Barum' 'Falken' 'Uniroyal' 'Dunlop'
 'Bridgestone' 'Firestone']
model ['Wintrac' "Winguard Snow'G WH2" 'SP901' 'Frigo HP2' 'Frigo 2'
 'Winter i*cept RS3 W462' 'Snowproof 1' 'SW608' 'Snowproof 2' 'Z507'
 'Wintercraft WP52' 'WinterContact TS 870' 'Polaris 6' 'Eurowinter HS02'
 'WinterExpert' 'Winter Sport 5' 'Blizzak LM005' 'Winterhawk 4'
 "Winguard Snow'G3 WH21"]
size ['205/55 R16']
load_index ['91' '94']
speed_index ['H' 'T' 'V']
fuel_index ['C' 'D' 'B']
wet_grip_index ['B' 'C' 'D' 'A']
noise_index ['B' 'A']
noise_level [70 72 71 69]
class ['Premium' 'Średnia' 'Ekonomiczna']
user_rating [5.4 5.3 5.1 5.2 5.6 5.  5.5]
price [376.99 310.   224.99 283.   239.   322.   335.   244.99 385.   227.
 320.   460.   289.   360.   399.   343.99 345.   402.99 450.99 329.13
 370.   277.99 389.  ]
oponeo
name ['Bridgestone Blizzak LM005 205/55 R16 91 H'
 'Michelin Alpin 7 205/55 R16 91 H' 'Dębica Frigo 2 205/55 R16 91 T'
 'Kormoran Snow 205/55 R16 91 H' 'Firemax FM805+ 205/55 R16 91 H'
 'Neolin NeoWinter 205/55 R16 91 V'
 'Compasal WinterBlazer HP 205/55 R16 91 H'
 'Imperial Snowdragon UHP 205/55 R16 91 H'
 'Imperial Snowdragon HP 205/55 R16 91 H'
 'Imperial Snowdragon HP 205/55 R16 91 V'
 'Neolin NeoWinter 205/55 R16 94 V XL'
 'Imperial Snowdragon UHP 205/55 R16 94 H XL'
 'Zeetex WH1000 205/55 R16 91 H' 'Kormoran Snow 205/55 R16 94 H XL'
 'Nankang Winter Activa SV-4 205/55 R16 94 V XL'
 'Laufenn I Fit+ 205/55 R16 91 T MFS' 'Laufenn I Fit+ 205/55 R16 91 H MFS'
 "Nexen Winguard Snow'G WH2 205/55 R16 91 T"
 'Nexen Winguard SnowG 3 WH21 205/55 R16 91 T'
 'Zeetex WH1000 205/55 R16 94 V XL' 'Barum Polaris 6 205/55 R16 91 T'
 'Nexen Winguard SnowG 3 WH21 205/55 R16 91 H'
 'Kumho WinterCraft WP52 205/55 R16 91 T'
 'Kumho WinterCraft WP52 205/55 R16 91 H'
 'Nokian Tyres Snowproof 1 205/55 R16 91 H'
 'Kleber Krisalp HP3 205/55 R16 91 H'
 'Nexen Winguard SnowG 3 WH21 205/55 R16 94 V XL'
 'Uniroyal WinterExpert 205/55 R16 91 T'
 'Hankook Winter i*cept RS3 W462 205/55 R16 91 T'
 'Uniroyal WinterExpert 205/55 R16 91 H'
 'Kleber Krisalp HP3 205/55 R16 91 T'
 'Yokohama BluEarth-Winter V906 205/55 R16 91 H'
 'Nokian Tyres Snowproof 2 205/55 R16 91 T'
 'Falken Eurowinter HS02 205/55 R16 91 H'
 'Vredestein Wintrac 205/55 R16 91 H'
 'Kleber Krisalp HP3 205/55 R16 94 H XL'
 'Vredestein Wintrac 205/55 R16 91 T'
 'Pirelli Powergy Winter 205/55 R16 91 H'
 'Uniroyal WinterExpert 205/55 R16 94 H XL'
 'Hankook Winter i*cept RS3 W462 205/55 R16 91 H'
 'Hankook Winter i*cept RS3 W462 205/55 R16 94 H XL'
 'Kleber Krisalp HP3 205/55 R16 94 V XL'
 'Goodyear Ultra Grip 8 205/55 R16 91 H'
 'Dunlop Winter Sport 5 205/55 R16 91 H'
 'Pirelli Cinturato Winter 2 205/55 R16 91 H'
 'Hankook Winter i*cept RS3 W462 205/55 R16 94 V XL'
 'Goodyear UltraGrip Performance 3 205/55 R16 91 H'
 'Goodyear UltraGrip Performance 3 205/55 R16 91 T'
 'Michelin Alpin 7 205/55 R16 91 T'
 'Bridgestone Blizzak 6 205/55 R16 91 H'
 'Continental WinterContact TS 870 205/55 R16 91 H'
 'Pirelli Cinturato Winter 2 205/55 R16 94 H XL'
 'Michelin Alpin 7 205/55 R16 94 H XL'
 'Continental WinterContact TS 870 205/55 R16 94 H XL'
 'Continental WinterContact TS 870 205/55 R16 94 V XL'
 'Sunwide SNOWIDE 205/55 R16 91 H' 'Tristar Snowpower HP 205/55 R16 91 H'
 'Ceat WinterDrive 205/55 R16 91 H' 'Fortune FSR-901 205/55 R16 94 H XL'
 'Arivo Winmaster ARW 1 205/55 R16 91 H'
 'Fortuna Gowin UHP 205/55 R16 91 H' 'DoubleStar DW08 205/55 R16 91 T'
 'Fortuna Gowin UHP 205/55 R16 91 V' 'Superia Bluewin UHP 205/55 R16 91 H'
 'Premiorri Via Maggiore 205/55 R16 91 T'
 'Tracmax X-Privilo S-130 205/55 R16 91 V'
 'Ceat WinterDrive 205/55 R16 94 V XL'
 'Triangle Winter X TW401 205/55 R16 94 V XL'
 'Fortuna Gowin UHP3 205/55 R16 94 H XL'
 'RoadX RX Frost WH01 205/55 R16 91 H'
 'Radar Dimax Alpine 205/55 R16 91 H'
 "Nexen Winguard Snow'G WH2 205/55 R16 91 H"
 'Premiorri ViaMaggiore Z Plus 205/55 R16 91 H'
 'DoubleStar DLA01 205/55 R16 94 V XL, FR' 'Trazano SW608 205/55 R16 91 H'
 'Linglong Grip Master Winter 205/55 R16 94 V XL'
 'RoadX RX Frost WH01 205/55 R16 94 V XL'
 'Sailun Ice Blazer Alpine+ 205/55 R16 91 H'
 'West Lake Z-507 205/55 R16 91 V'
 'Sunny Wintermaxx NW211 205/55 R16 91 H'
 'Sailun Ice Blazer Alpine+ 205/55 R16 94 H XL'
 'Dębica Frigo HP2 205/55 R16 91 H' 'Minerva Frostrack HP 205/55 R16 91 V'
 'Rotalla S210 205/55 R16 91 H' 'Matador MP93 Nordicca 205/55 R16 91 H'
 'Aplus A701 205/55 R16 91 H' 'Tracmax S210 205/55 R16 94 H XL'
 'Linglong Green-Max Winter HP 205/55 R16 94 H'
 'Apollo Alnac 4G Winter 205/55 R16 91 H'
 'Goodride ZuperSnow Z-507 205/55 R16 91 V'
 'Cooper WM-SA2+ 205/55 R16 91 T'
 'Linglong Grip Master Winter 205/55 R16 91 H'
 'Goodride SW608 205/55 R16 91 H' 'Nexen Winguard Sport 2 205/55 R16 91 H'
 'Kormoran Snow 205/55 R16 91 T' 'Apollo Alnac 4G Winter 205/55 R16 91 T'
 'Superia Bluewin UHP3 205/55 R16 94 H XL'
 'Matador MP93 Nordicca 205/55 R16 91 T'
 'Mastersteel WINTER + W3 205/55 R16 91 H'
 'Firestone Winterhawk 4 205/55 R16 91 T'
 'Fortune FSR-901 205/55 R16 91 H'
 'Tristar Snowpower UHP 205/55 R16 94 H XL'
 'Tristar Snowpower HP 205/55 R16 91 V'
 'Radar Dimax Alpine 205/55 R16 94 H' 'Syron Everest 2 205/55 R16 91 T'
 'GT Radial WinterPro 2 EVO 205/55 R16 91 H'
 'Tomket Snowroad 205/55 R16 91 H' 'Delinte WD1 205/55 R16 91 H'
 'Barum Polaris 6 205/55 R16 91 H' 'Sava Eskimo S3+ 205/55 R16 91 T'
 'Landsail Winter Lander 205/55 R16 91 H'
 'West Lake SW608 205/55 R16 91 H' 'Ovation W586 205/55 R16 91 H'
 'Tomket Snowroad PRO 3 205/55 R16 94 H XL'
 'Matador MP93 Nordicca 205/55 R16 94 V XL'
 'Nankang SV-3 205/55 R16 94 H XL' 'Austone SP901 205/55 R16 91 H'
 'Riken Snow 205/55 R16 91 T' 'Kingstar SW40 205/55 R16 94 T'
 'Minerva Frostrack UHP 205/55 R16 91 H'
 'Davanti WINTOURA 205/55 R16 91 T' 'Evergreen EW66 205/55 R16 91 H'
 'Maxxis Premitra Snow WP6 205/55 R16 91 H'
 'Nokian Tyres Snowproof 2 205/55 R16 91 H'
 'Toyo Observe S944 205/55 R16 91 H'
 'Nordexx WinterSafe 2 205/55 R16 91 H' 'Torque PCR TQ022 205/55 R16 91 H'
 'Minerva Frostrack UHP 205/55 R16 94 H XL'
 'Kenda Wintergen 2 KR501 205/55 R16 94 H XL'
 'Kenda Wintergen 2 KR501 205/55 R16 91 T'
 'Apollo Alnac 4G Winter 205/55 R16 94 H XL'
 'Windforce SnowBlazer 205/55 R16 91 H' 'Goodride SW618 205/55 R16 91 H'
 'Dunlop Winter Sport 5 205/55 R16 91 T'
 'BFGoodrich G-Force Winter 2 205/55 R16 94 H XL'
 'Maxxis Premitra Snow WP6 205/55 R16 94 V XL'
 'Falken Eurowinter HS01 205/55 R16 91 T'
 'Kumho WinterCraft WP51 205/55 R16 91 H RUN ON FLAT'
 'Firestone Winterhawk 4 205/55 R16 91 H'
 'Sava Eskimo HP2 205/55 R16 91 H'
 'Laufenn I Fit+ 205/55 R16 94 H XL, MFS'
 'GT Radial Champiro WinterPro HP 205/55 R16 94 V XL'
 'Arivo Winmaster ARW 2 205/55 R16 91 H'
 'Yokohama BluEarth-Winter V906 205/55 R16 91 T'
 'Vredestein Wintrac 205/55 R16 94 H XL'
 'Semperit Speed-Grip 5 205/55 R16 91 T'
 'Fulda Kristall Control HP2 205/55 R16 91 H'
 'Vredestein Snowtrac 5 205/55 R16 91 H'
 'Continental WinterContact TS 870 205/55 R16 91 T'
 'Hankook Winter i*cept RS3 W462B 205/55 R16 91 H RUN ON FLAT'
 'Firestone Winterhawk 4 205/55 R16 94 H XL'
 'Sava Eskimo HP2 205/55 R16 94 H XL'
 'Cooper Discoverer Winter 205/55 R16 94 V XL'
 'Vredestein Wintrac 205/55 R16 94 V XL'
 'Vredestein Snowtrac 5 205/55 R16 91 H VW'
 'BFGoodrich G-Force Winter 2 205/55 R16 91 H'
 'Bridgestone Blizzak LM001 EVO 205/55 R16 91 H'
 'Falken Eurowinter HS01 205/55 R16 91 H RUN ON FLAT'
 'Firestone Winterhawk 4 205/55 R16 94 V XL'
 'Lanvigator Snowpower 205/55 R16 91 H'
 'Fulda KRISTALL MONTERO 3 205/55 R16 91 T'
 'Viking WinTech 205/55 R16 91 H' 'Mirage MR-W562 205/55 R16 91 H'
 'Cooper Discoverer Winter 205/55 R16 91 H'
 'Toyo Observe S944 205/55 R16 94 V XL' 'Barum Polaris 5 205/55 R16 91 H'
 'Cooper Weather-Master WSC 205/55 R16 91 T'
 'Barum Polaris 6 205/55 R16 94 H XL'
 'Bridgestone Blizzak LM005 205/55 R16 91 T'
 'Bridgestone Blizzak 6 205/55 R16 94 H XL'
 'Kumho WinterCraft WP52 205/55 R16 94 H XL'
 'Mazzini Snow Leopard 205/55 R16 91 T'
 'Uniroyal WinterExpert 205/55 R16 94 V XL'
 'Dunlop SP WINTER SPORT 3D 205/55 R16 91 H *'
 'Semperit Speed-Grip 5 205/55 R16 91 H'
 'Dunlop Winter Sport 5 205/55 R16 94 H XL'
 'Pirelli Cinturato Winter 205/55 R16 91 H'
 'Bridgestone Blizzak LM001 205/55 R16 91 H *'
 'Dunlop SP Winter Sport 4D 205/55 R16 91 H AO MFS'
 'Yokohama BluEarth-Winter V906 205/55 R16 94 H XL'
 'Viking WinTech 205/55 R16 91 T'
 'Goodyear UG Performance G1 205/55 R16 91 H AO'
 'Dunlop SP Winter Sport 4D 205/55 R16 91 H MO'
 'Pirelli SottoZero Serie 3 205/55 R16 91 H RUN ON FLAT *'
 "Nexen Winguard Snow'G WH2 205/55 R16 94 V XL"
 'Goodyear Ultra Grip 9+ 205/55 R16 91 H'
 'Nokian Tyres Snowproof 2 205/55 R16 94 H XL'
 'Yokohama BluEarth-Winter V906 205/55 R16 94 V XL'
 'Falken Eurowinter HS02 205/55 R16 94 V XL'
 'Continental WinterContact TS 860 S 205/55 R16 91 H RUN ON FLAT , *'
 'Fulda Kristall Control HP2 205/55 R16 94 V XL'
 'Goodyear UltraGrip Performance 3 205/55 R16 94 H XL'
 'Dunlop Winter Sport 5 205/55 R16 94 V XL'
 'Continental ContiWinterContact TS830 P 205/55 R16 91 H MO'
 'Dunlop SP WINTER SPORT 3D 205/55 R16 91 H RUN ON FLAT MOE'
 'Continental ContiWinterContact TS830 P 205/55 R16 91 H AO'
 'Bridgestone Blizzak LM001 205/55 R16 91 H RUN ON FLAT *'
 'Semperit Speed-Grip 5 205/55 R16 94 V XL'
 'Bridgestone Blizzak LM005 205/55 R16 94 H XL'
 'Bridgestone Blizzak LM005 DriveGuard 205/55 R16 94 V RUN ON FLAT XL'
 'Pirelli Cinturato Winter 2 205/55 R16 91 T'
 'Bridgestone Blizzak 6 205/55 R16 94 V XL'
 'Taurus Winter 205/55 R16 91 T'
 'Pirelli Snowcontrol Serie III 205/55 R16 91 H'
 'Barum Polaris 5 205/55 R16 91 T'
 'Goodyear UltraGrip Performance 3 205/55 R16 94 V XL'
 'BFGoodrich G-Force Winter 2 205/55 R16 91 T'
 'Taurus Winter 205/55 R16 94 H XL' 'Taurus Winter 205/55 R16 91 H'
 'Goodyear Ultra Grip 9+ 205/55 R16 91 T'
 'Michelin ALPIN 5 205/55 R16 91 H N0'
 'Goodyear UG Performance 2 205/55 R16 91 H RUN ON FLAT FP'
 'Bridgestone Blizzak LM005 205/55 R16 94 V XL'
 'Barum Polaris 5 205/55 R16 94 V XL'
 'Michelin ALPIN 5 205/55 R16 91 H RUN ON FLAT']
brand ['Bridgestone' 'Michelin' 'Dębica' 'Kormoran' 'Firemax' 'Neolin'
 'Compasal' 'Imperial' 'Zeetex' 'Nankang' 'Laufenn' 'Nexen' 'Barum'
 'Kumho' 'Nokian Tyres' 'Kleber' 'Uniroyal' 'Hankook' 'Yokohama' 'Falken'
 'Vredestein' 'Pirelli' 'Goodyear' 'Dunlop' 'Continental' 'Sunwide'
 'Tristar' 'Ceat' 'Fortune' 'Arivo' 'Fortuna' 'DoubleStar' 'Superia'
 'Premiorri' 'Tracmax' 'Triangle' 'RoadX' 'Radar' 'Trazano' 'Linglong'
 'Sailun' 'West Lake' 'Sunny' 'Minerva' 'Rotalla' 'Matador' 'Aplus'
 'Apollo' 'Goodride' 'Cooper' 'Mastersteel' 'Firestone' 'Syron'
 'GT Radial' 'Tomket' 'Delinte' 'Sava' 'Landsail' 'Ovation' 'Austone'
 'Riken' 'Kingstar' 'Davanti' 'Evergreen' 'Maxxis' 'Toyo' 'Nordexx'
 'Torque' 'Kenda' 'Windforce' 'BFGoodrich' 'Semperit' 'Fulda' 'Lanvigator'
 'Viking' 'Mirage' 'Mazzini' 'Taurus']
model ['Blizzak LM005' 'Alpin 7' 'Frigo 2' 'Snow' 'FM805+' 'NeoWinter'
 'WinterBlazer HP' 'Snowdragon UHP' 'Snowdragon HP' 'WH1000'
 'Winter Activa SV-4' 'I Fit+' "Winguard Snow'G WH2"
 'Winguard SnowG 3 WH21' 'Polaris 6' 'WinterCraft WP52' 'Snowproof 1'
 'Krisalp HP3' 'WinterExpert' 'Winter i*cept RS3 W462'
 'BluEarth-Winter V906' 'Snowproof 2' 'Eurowinter HS02' 'Wintrac'
 'Powergy Winter' 'Ultra Grip 8' 'Winter Sport 5' 'Cinturato Winter 2'
 'UltraGrip Performance 3' 'Blizzak 6' 'WinterContact TS 870' 'SNOWIDE'
 'Snowpower HP' 'WinterDrive' 'FSR-901' 'Winmaster ARW 1' 'Gowin UHP'
 'DW08' 'Bluewin UHP' 'Via Maggiore' 'X-Privilo S-130' 'Winter X TW401'
 'Gowin UHP3' 'RX Frost WH01' 'Dimax Alpine' 'ViaMaggiore Z Plus' 'DLA01'
 'SW608' 'Grip Master Winter' 'Ice Blazer Alpine+' 'Z-507'
 'Wintermaxx NW211' 'Frigo HP2' 'Frostrack HP' 'S210' 'MP93 Nordicca'
 'A701' 'Green-Max Winter HP' 'Alnac 4G Winter' 'ZuperSnow Z-507'
 'WM-SA2+' 'Winguard Sport 2' 'Bluewin UHP3' 'WINTER + W3' 'Winterhawk 4'
 'Snowpower UHP' 'Everest 2' 'WinterPro 2 EVO' 'Snowroad' 'WD1'
 'Eskimo S3+' 'Winter Lander' 'W586' 'Snowroad PRO 3' 'SV-3' 'SP901'
 'SW40' 'Frostrack UHP' 'WINTOURA' 'EW66' 'Premitra Snow WP6'
 'Observe S944' 'WinterSafe 2' 'PCR TQ022' 'Wintergen 2 KR501'
 'SnowBlazer' 'SW618' 'G-Force Winter 2' 'Eurowinter HS01'
 'WinterCraft WP51' 'Eskimo HP2' 'Champiro WinterPro HP' 'Winmaster ARW 2'
 'Speed-Grip 5' 'Kristall Control HP2' 'Snowtrac 5'
 'Winter i*cept RS3 W462B' 'Discoverer Winter' 'Blizzak LM001 EVO'
 'Snowpower' 'KRISTALL MONTERO 3' 'WinTech' 'MR-W562' 'Polaris 5'
 'Weather-Master WSC' 'Snow Leopard' 'SP WINTER SPORT 3D'
 'Cinturato Winter' 'Blizzak LM001' 'SP Winter Sport 4D'
 'UG Performance G1' 'SottoZero Serie 3' 'Ultra Grip 9+'
 'WinterContact TS 860 S' 'ContiWinterContact TS830 P'
 'Blizzak LM005 DriveGuard' 'Winter' 'Snowcontrol Serie III' 'ALPIN 5'
 'UG Performance 2']
size ['205/55 R16']
load_index ['91' '94']
speed_index ['H' 'T' 'V']
fuel_index ['C' 'D' 'B' 'E' 'F']
wet_grip_index ['A' 'B' 'C' 'D' 'E' 'F']
noise_index ['B' 'A' None]
noise_level [71 72 67 70 69 68 73]
class ['Premium' 'Ekonomiczna' 'Średnia']
user_rating ['4,7' '4,8' '4,2' '4,5' '4,4' None '4,3' '4,0' '5,0' '4,6' '3,9' '3,7'
 '3,8' '2,4' '2,6' '4,1' '3,6']
price ['459' '467' '252' '249' '209' '191' '207' '215' '216' '217' '218' '220'
 '229' '254' '257' '264' '269' '293' '297' '299' '301' '307' '332' '337'
 '338' '339' '340' '342' '346' '347' '348' '353' '357' '359' '373' '379'
 '382' '383' '387' '388' '390' '392' '393' '407' '409' '424' '432' '447'
 '452' '466' '468' '474' '477' '520' '555' '597' '253' '258' '267' '270'
 '271' '273' '274' '279' '280' '287' '294' '298' '300' '304' '305' '309'
 '311' '315' '317' '318' '320' '322' '325' '328' '330' '331' '333' '336'
 '341' '345' '354' '356' '364' '365' '367' '368' '369' '371' '375' '377'
 '380' '385' '395' '397' '401' '402' '404' '405' '410' '415' '418' '421'
 '423' '434' '435' '436' '437' '439' '443' '449' '453' '455' '460' '461'
 '475' '478' '483' '488' '490' '492' '494' '497' '504' '505' '506' '509'
 '513' '517' '519' '521' '524' '532' '533' '534' '536' '550' '551' '552'
 '554' '556' '560' '567' '573' '574' '575' '577' '582' '584' '589' '600'
 '608' '612' '618' '620' '621' '626' '630' '631' '640' '641' '654' '659'
 '661' '666' '667' '684' '691' '700' '703' '742' '753' '778' '854' '972'
 '1 100']